services:
  backend:
    build: ./backend
    container_name: satisfactory-backend
    ports:
      - "5000:5000"       # <== So that the host can directly hit port 5000
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - ./backend/.env.production

  db:
    image: postgres:17
    container_name: satisfactory_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbPass
      POSTGRES_DB: satisfactory_app_db
    ports:
      - "5434:5432"                         # Expose PostgreSQL on port 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
