# Satisfactory_App/docker-compose.yml

services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - type: bind
#        source: ./nginx.conf
#        target: /etc/nginx/nginx.conf
#        read_only: true
#    depends_on:
##      - frontend
#      - backend
#    networks:
#      - app-network
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: satisfactory-backend
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - ./backend/.env.production

  db:
    image: postgres:17
    container_name: satisfactory_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbPass
      POSTGRES_DB: satisfactory_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
