"""added parent/child relationship 'line_id' to production_line_targets table

Revision ID: 2a559f2ac881
Revises: 41d09b6999b1
Create Date: 2024-12-03 17:19:17.234882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a559f2ac881'
down_revision = '41d09b6999b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_line_targets', sa.Column('line_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'production_line_targets', 'production_lines', ['line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_line_targets', type_='foreignkey')
    op.drop_column('production_line_targets', 'line_id')
    # ### end Alembic commands ###
