"""removed mandatory column from user_recipes table and added excluded

Revision ID: 41d09b6999b1
Revises: 56a6f4b959b7
Create Date: 2024-12-03 16:43:13.416026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d09b6999b1'
down_revision = '56a6f4b959b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_recipes', sa.Column('excluded', sa.Boolean(), nullable=False))
    op.drop_column('user_recipes', 'is_mandatory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_recipes', sa.Column('is_mandatory', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user_recipes', 'excluded')
    # ### end Alembic commands ###
