"""removed eronious created_at from user_recipes table and changed production_line_item table to production_line_target table

Revision ID: 56a6f4b959b7
Revises: e80a62f05643
Create Date: 2024-12-03 16:31:01.909066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56a6f4b959b7'
down_revision = 'e80a62f05643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('production_line_items', 'production_line_targets')
    op.drop_column('user_recipes', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_recipes', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.rename_table('production_line_targets', 'production_line_items')
    # ### end Alembic commands ###
