"""adjusted user_recipes table to have proper relationship with user table and added id as primary key

Revision ID: a1dd4d8869cf
Revises: 2a559f2ac881
Create Date: 2024-12-03 17:49:09.993824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1dd4d8869cf'
down_revision = '2a559f2ac881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_recipes', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_recipes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_recipes_user_key_fkey', 'user_recipes', type_='foreignkey')
    op.create_foreign_key(None, 'user_recipes', 'users', ['user_id'], ['id'])
    op.drop_column('user_recipes', 'user_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_recipes', sa.Column('user_key', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_recipes', type_='foreignkey')
    op.create_foreign_key('user_recipes_user_key_fkey', 'user_recipes', 'users', ['user_key'], ['id'])
    op.drop_column('user_recipes', 'user_id')
    op.drop_column('user_recipes', 'id')
    # ### end Alembic commands ###
