"""Rename component to sinkable and add new components table

Revision ID: c0f6b53d5d31
Revises: 7576607e686d
Create Date: 2024-10-18 17:30:34.900803

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c0f6b53d5d31'
down_revision = '7576607e686d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the component table to sinkable
    op.rename_table('components', 'sinkables')

    op.create_table('components',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), sa.ForeignKey('items.id'), nullable=False),
        sa.Column('building_id', sa.Integer(), sa.ForeignKey('buildings.id'), nullable=False),
        sa.Column('recipe_id', sa.Integer(), sa.ForeignKey('recipes.id'), nullable=False),
        sa.Column('recipe_type', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
                    )


def downgrade():
    # Reverse the rename
    op.rename_table('sinkable', 'component')

    # Drop the components table
    op.drop_table('components')
