"""updated production_lines table to reflect type def on frontend

Revision ID: d3735f67e60f
Revises: 39cb02ed207d
Create Date: 2024-12-04 13:49:52.943110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3735f67e60f'
down_revision = '39cb02ed207d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lines', sa.Column('line_id_frontend', sa.String(), nullable=False))
    op.add_column('production_lines', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('production_lines', 'line_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lines', sa.Column('line_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('production_lines', 'name')
    op.drop_column('production_lines', 'line_id_frontend')
    # ### end Alembic commands ###
