"""deleting user_recipes table again

Revision ID: e959b8ac6ad3
Revises: 1dada2e81d58
Create Date: 2024-12-04 12:36:28.297991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e959b8ac6ad3'
down_revision = '1dada2e81d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipes',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('known', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('excluded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('preferred', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='user_recipes_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_recipes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pk_user_recipes')
    )
    # ### end Alembic commands ###
