"""allowing item_id to be nullable

Revision ID: f62550756d0c
Revises: 9c5b96b89e0f
Create Date: 2024-12-09 14:53:51.004456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62550756d0c'
down_revision = '9c5b96b89e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_line_targets', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_line_targets', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
