name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH to VPS
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Add VPS to known hosts
      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H 45.77.202.161 >> ~/.ssh/known_hosts

      # Stop the running containers on VPS
      - name: Stop running containers on VPS
        run: |
          ssh root@45.77.202.161 << 'EOF'
          cd /root/projects/SatisfactoryApp
          docker-compose down
          EOF

      # Sync files using git pull
      - name: Sync files with git pull
        run: |
          ssh root@45.77.202.161 << 'EOF'
          cd /root/projects/SatisfactoryApp
          git pull origin main
          EOF

      # SSH into VPS and deploy
      - name: Deploy backend
        run: |
          ssh root@45.77.202.161 << 'EOF'
          cd /root/projects/SatisfactoryApp
          docker-compose -f docker-compose.yml up --build
          EOF
